// Generated by CoffeeScript 1.3.3
var app, assets, express, fs, phantom, port, publicDir, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

fs = require('fs');

phantom = require('phantom');

publicDir = "./public";

app = express();

app.use(assets());

app.use("/phimages", express["static"]('./public/phimages'));

app.use("/images", express["static"]('./public/images'));

app.set("view engine", "jade");

app.get('/', function(req, res) {
  return res.render('index');
});

app.get('/render', function(req, res) {
  return res.render('render', {
    layout: 'renderlayout'
  });
});

app.get('/save', function(req, res) {
  var fileDir, fileUrl, height, host, imgurl, orbs;
  fileDir = "" + publicDir + "/phimages/rendered.png";
  fileUrl = "/phimages/rendered.png";
  orbs = req.query.orbs;
  imgurl = req.query.imgurl;
  height = parseInt(req.query.stageheight) + 30;
  host = req.headers.host;
  return phantom.create(function(ph) {
    return ph.createPage(function(page) {
      page.set('clipRect', {
        top: 40,
        left: 20,
        width: 580,
        height: height
      });
      return page.open("http://" + host + "/render?imgurl=" + imgurl + "&orbs=" + orbs, function() {
        return setTimeout(function() {
          return page.render(fileDir, function() {
            console.log("Image Created");
            ph.exit();
            return res.send('200', {
              redirect: '/phimages/rendered.png'
            });
          });
        }, 1000);
      });
    });
  });
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
